@extends('create-form')
@section('form')
@method('PUT')
@include('input_readonly',['value'=>$d->id,'id'=>'id','label'=>'ID Karyawan'])
@include('input_readonly',['value'=>$d->nik,'id'=>'nik','label'=>'NIK'])
@include('input_readonly',['value'=>$d->nama,'id'=>'nama','label'=>'Nama'])
@include('input_readonly',['value'=>$d->no_hp,'id'=>'no_hp','label'=>'No HP'])
@include('input_readonly',['value'=>$d->no_darurat,'id'=>'no_darurat','label'=>'No Darurat'])
@include('input_readonly',['value'=>$d->jabatan,'id'=>'jabatan','label'=>'Jabatan'])
@include('textarea_readonly',['value'=>$d->alamat,'id'=>'alamat','label'=>'Alamat'])
@include('input_readonly',['value'=>$d->armada,'id'=>'armada','label'=>'Armada'])
@include('input_readonly',['value'=>$d->gaji_pokok,'id'=>'gaji_pokok','label'=>'Gaji Pokok'])
@include('input_readonly',['value'=>$d->um_harian,'id'=>'um_harian','label'=>'UM Harian'])
@include('input_readonly',['value'=>$d->rate_lembur,'id'=>'rate_lembur','label'=>'Rate Lembur'])
@include('input_readonly',['value'=>$d->jenis,'id'=>'jenis','label'=>'Jenis Karyawan'])
@if($d->jenis == 'Operator')
@include('input_readonly',['value'=>$d->rate_per_jam,'id'=>'rate_per_jam','label'=>'Rate Per Jam'])
@elseif($d->jenis == 'Sopir')
@include('input_readonly',['value'=>$d->insentif,'id'=>'insentif','label'=>'Insentif'])
@endif
@endsection